/**
 * Created by johnuiterwyk on 2/22/16.
 */

export default {
    LOGIN_REQUEST_SENT:"LOGIN_REQUEST_SENT",
    LOGIN_SUCCES_RECIEVED:"LOGIN_SUCCES_RECIEVED",
    LOGIN_ERROR_RECIEVED:"LOGIN_ERROR_RECIEVED",
    LOGOUT:"LOGOUT",

    SIGNUP_REQUEST_SENT:"SIGNUP_REQUEST_SENT",
    SIGNUP_SUCCES_RECIEVED:"SIGNUP_SUCCES_RECIEVED",
    SIGNUP_ERROR_RECIEVED:"SIGNUP_ERROR_RECIEVED",

    TRIP_LIST_GET_SUCCESS:"TRIPS_LIST_RECIEVED",
    TRIP_CREATE_SUCCESS:"TRIP_CREATE_SUCCESS",
    TRIP_CREATE_FAIL:"TRIP_CREATE_FAIL",
    TRIP_DELETED:"TRIP_DELETED",
    TRIP_LOAD_FOR_EDIT:"TRIP_LOAD_FOR_EDIT",
    TRIP_CANCEL_EDIT:"TRIP_CANCEL_EDIT",
    TRIP_UPDATE_SUCCESS:"TRIP_UPDATE_SUCCESS",
    TRIP_UPDATE_FAIL:"TRIP_UPDATE_FAIL",

    TRIP_FILTER_STRING_UPDATE:"TRIP_FILTER_STRING_UPDATE",

    USER_LIST_GET_SUCCESS:"USER_LIST_GET_SUCCESS",
    USER_CREATE_SUCCESS:"USER_CREATE_SUCCESS",
    USER_CREATE_FAIL:"USER_CREATE_FAIL",
    USER_DELETED:"USER_DELETED",
    USER_LOAD_FOR_EDIT:"USER_LOAD_FOR_EDIT",
    USER_CANCEL_EDIT:"USER_CANCEL_EDIT",
    USER_UPDATE_SUCCESS:"USER_UPDATE_SUCCESS",
    USER_UPDATE_FAIL:"USER_UPDATE_FAIL"
}

