/**
 * Created by johnuiterwyk on 2/22/16.
 */

export default {
    LOGIN_REQUEST_SENT:"LOGIN_REQUEST_SENT",
    LOGIN_SUCCES_RECIEVED:"LOGIN_SUCCES_RECIEVED",
    LOGIN_ERROR_RECIEVED:"LOGIN_ERROR_RECIEVED",
    LOGOUT:"LOGOUT",

    SIGNUP_REQUEST_SENT:"SIGNUP_REQUEST_SENT",
    SIGNUP_SUCCES_RECIEVED:"SIGNUP_SUCCES_RECIEVED",
    SIGNUP_ERROR_RECIEVED:"SIGNUP_ERROR_RECIEVED",

    TRIP_LIST_GET_SUCCESS:"TRIPS_LIST_RECIEVED",
    TRIP_CREATE_SUCCESS:"TRIP_CREATE_SUCCESS",
    TRIP_CREATE_FAIL:"TRIP_CREATE_FAIL",
    TRIP_DELETED:"TRIP_DELETED",
    TRIP_UPDATE_SUCCESS:"TRIP_UPDATE_SUCCESS",
    TRIP_UPDATE_FAIL:"TRIP_UPDATE_FAIL"

}