/**
 * Created by johnuiterwyk on 2/22/16.
 */

export default {
    LOGIN_REQUEST_SENT:"LOGIN_REQUEST_SENT",
    LOGIN_SUCCES_RECIEVED:"LOGIN_SUCCES_RECIEVED",
    LOGIN_ERROR_RECIEVED:"LOGIN_ERROR_RECIEVED",
    LOGOUT:"LOGOUT",

    SIGNUP_REQUEST_SENT:"SIGNUP_REQUEST_SENT",
    SIGNUP_SUCCES_RECIEVED:"SIGNUP_SUCCES_RECIEVED",
    SIGNUP_ERROR_RECIEVED:"SIGNUP_ERROR_RECIEVED"

}